dummy.name=Dummy Tool
dummy.version=1.0-SNAPSHOT
dummy.desc=A basic Joget plugin for GitHub workflow practice.
dummy.label=Dummy Tool
dummy.config=Configuration
dummy.message=Message
dummy.defaultMessage=Hello from dummyrepo plugin
